In [1]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

In [2]:
import random

np.random.seed(42)

process_names = [
    "Order Processing",
    "Invoice Approval",
    "Customer Support",
    "Inventory Management",
    "Recruitment",
    "Procurement",
    "Payroll Processing"
]

departments = [
    "Operations",
    "Finance",
    "HR",
    "Customer Service",
    "Supply Chain",
    "IT"
]

owners = [
    "John",
    "Mary",
    "David",
    "Sarah",
    "Michael",
    "Emma",
    "James"
]

data = []

for i in range(100):

    start_date = datetime(2025,1,1) + timedelta(days=np.random.randint(0,365))
    cycle_time = np.random.randint(2,24)

    end_date = start_date + timedelta(hours=cycle_time)

    task_volume = np.random.randint(100,1000)

    completed = np.random.randint(
        int(task_volume*0.7),
        task_volume
    )

    productivity = round((completed/task_volume)*100,2)

    errors = np.random.randint(0,20)

    rework = np.random.randint(0,10)

    process_cost = np.random.randint(1000,10000)

    complaints = np.random.randint(0,15)

    sla_achieved = np.random.randint(75,100)

    data.append([
        f"P{i+1:03}",
        random.choice(process_names),
        random.choice(departments),
        random.choice(owners),
        start_date.date(),
        end_date.date(),
        cycle_time,
        np.random.randint(4,20),
        np.random.randint(1,10),
        task_volume,
        completed,
        productivity,
        errors,
        rework,
        process_cost,
        complaints,
        95,
        sla_achieved,
        random.choice([
            "Completed",
            "Delayed",
            "In Progress"
        ]),
        random.choice([
            "Automation",
            "Training",
            "Process Redesign",
            "Resource Allocation"
        ])
    ])

columns = [
    "Process ID",
    "Process Name",
    "Department",
    "Process Owner",
    "Start Date",
    "End Date",
    "Cycle Time",
    "Standard Cycle Time",
    "Employee Assigned",
    "Task Volume",
    "Tasks Completed",
    "Productivity %",
    "Error Count",
    "Rework Count",
    "Process Cost",
    "Customer Complaints",
    "SLA Target",
    "SLA Achieved",
    "Process Status",
    "Improvement Opportunity"
]

df = pd.DataFrame(data, columns=columns)

df.head()

,Process ID,Process Name,Department,Process Owner,Start Date,End Date,Cycle Time,Standard Cycle Time,Employee Assigned,Task Volume,Tasks Completed,Productivity %,Error Count,Rework Count,Process Cost,Customer Complaints,SLA Target,SLA Achieved,Process Status,Improvement Opportunity
0,P001,Payroll Processing,Supply Chain,Michael,2025-04-13,2025-04-13,21,10,8,960,942,98.12,10,7,6734,9,95,93,Completed,Process Redesign
1,P002,Customer Support,Finance,Emma,2025-04-10,2025-04-10,9,4,6,763,664,87.02,1,7,7949,1,95,95,Delayed,Training
2,P003,Procurement,Supply Chain,John,2025-09-10,2025-09-10,13,19,9,956,717,75.00,9,2,2899,6,95,94,Delayed,Resource Allocation
3,P004,Order Processing,Customer Service,Emma,2025-05-11,2025-05-11,6,15,2,918,776,84.53,8,6,6393,3,95,99,In Progress,Automation
4,P005,Invoice Approval,IT,Mary,2025-09-22,2025-09-22,22,17,1,997,788,79.04,14,6,1775,14,95,77,In Progress,Process Redesign

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Process ID               100 non-null    object
 1   Process Name             100 non-null    object
 2   Department               100 non-null    object
 3   Process Owner            100 non-null    object
 4   Start Date               100 non-null    object
 5   End Date                 100 non-null    object
 6   Cycle Time               100 non-null    int64
 7   Standard Cycle Time      100 non-null    int64
 8   Employee Assigned        100 non-null    int64
 9   Task Volume              100 non-null    int64
 10  Tasks Completed          100 non-null    int64
 11  Productivity %           100 non-null    float64
 12  Error Count              100 non-null    int64
 13  Rework Count             100 non-null    int64
 14  Process Cost             100 non-null    int64
 15  Customer Complaints      100 non-null    int64
 16  SLA Target               100 non-null    int64
 17  SLA Achieved             100 non-null    int64
 18  Process Status           100 non-null    object
 19  Improvement Opportunity  100 non-null    object
dtypes: float64(1), int64(11), object(8)
memory usage: 15.8+ KB

In [4]:
df.isnull().sum()

Process ID                 0
Process Name               0
Department                 0
Process Owner              0
Start Date                 0
End Date                   0
Cycle Time                 0
Standard Cycle Time        0
Employee Assigned          0
Task Volume                0
Tasks Completed            0
Productivity %             0
Error Count                0
Rework Count               0
Process Cost               0
Customer Complaints        0
SLA Target                 0
SLA Achieved               0
Process Status             0
Improvement Opportunity    0
dtype: int64

In [5]:
process_efficiency = (
    df["Standard Cycle Time"].mean()
    /
    df["Cycle Time"].mean()
) * 100

task_completion_rate = (
    df["Tasks Completed"].sum()
    /
    df["Task Volume"].sum()
) * 100

error_rate = (
    df["Error Count"].sum()
    /
    df["Task Volume"].sum()
) * 100

rework_rate = (
    df["Rework Count"].sum()
    /
    df["Task Volume"].sum()
) * 100

sla_rate = df["SLA Achieved"].mean()

avg_productivity = df["Productivity %"].mean()

total_cost = df["Process Cost"].sum()

print("Process Efficiency:", round(process_efficiency,2))
print("Task Completion:", round(task_completion_rate,2))
print("Error Rate:", round(error_rate,2))
print("Rework Rate:", round(rework_rate,2))
print("Average SLA:", round(sla_rate,2))
print("Productivity:", round(avg_productivity,2))
print("Total Cost:", total_cost)

Process Efficiency: 90.69
Task Completion: 85.74
Error Rate: 1.53
Rework Rate: 0.78
Average SLA: 86.97
Productivity: 84.91
Total Cost: 519003

In [6]:
department_summary = df.groupby("Department").agg({
    "Process Cost":"sum",
    "Productivity %":"mean",
    "Error Count":"sum",
    "Tasks Completed":"sum"
})

department_summary

                  Process Cost  Productivity %  Error Count  Tasks Completed
Department
Customer Service         78214       83.345625          116             6852
Finance                  70941       84.452941          185             8572
HR                      100722       85.535882          143             7915
IT                      123003       88.835000          208            14257
Operations               48702       82.610000           88             4799
Supply Chain             97421       82.594737          193             9843

In [7]:
process_summary = df.groupby("Process Name").agg({
    "Cycle Time":"mean",
    "Process Cost":"sum",
    "Error Count":"sum",
    "Productivity %":"mean"
})

process_summary

                      Cycle Time  Process Cost  Error Count  Productivity %
Process Name
Customer Support       12.187500         88150          153       87.902500
Inventory Management   12.625000         86410          196       79.857500
Invoice Approval       13.333333         54160          109       80.857500
Order Processing       12.555556         54664           91       86.233333
Payroll Processing     14.466667         78843          100       87.856667
Procurement            12.461538         60793          131       86.954615
Recruitment            12.631579         95983          153       84.825789

In [8]:
bottlenecks = df[
    df["Cycle Time"] >
    df["Cycle Time"].mean()
]

bottlenecks[
    [
        "Process ID",
        "Process Name",
        "Department",
        "Cycle Time"
    ]
].head(20)

   Process ID          Process Name        Department  Cycle Time
0        P001    Payroll Processing      Supply Chain          21
2        P003           Procurement      Supply Chain          13
4        P005      Invoice Approval                IT          22
7        P008           Procurement      Supply Chain          17
8        P009      Invoice Approval  Customer Service          16
12       P013           Recruitment                IT          15
13       P014    Payroll Processing      Supply Chain          21
17       P018           Procurement           Finance          21
21       P022    Payroll Processing                HR          17
22       P023      Customer Support      Supply Chain          21
24       P025  Inventory Management      Supply Chain          18
25       P026      Invoice Approval                HR          20
27       P028           Procurement        Operations          19
28       P029    Payroll Processing  Customer Service          21
29       P030      Order Processing  Customer Service          15
30       P031           Procurement           Finance          16
31       P032      Invoice Approval                HR          15
33       P034      Customer Support        Operations          19
36       P037    Payroll Processing           Finance          21
37       P038    Payroll Processing                HR          20

In [9]:
high_cost = df.sort_values(
    by="Process Cost",
    ascending=False
)

high_cost.head(10)

,Process ID,Process Name,Department,Process Owner,Start Date,End Date,Cycle Time,Standard Cycle Time,Employee Assigned,Task Volume,Tasks Completed,Productivity %,Error Count,Rework Count,Process Cost,Customer Complaints,SLA Target,SLA Achieved,Process Status,Improvement Opportunity
48,P049,Order Processing,Supply Chain,David,2025-09-10,2025-09-10,20,13,2,853,631,73.97,16,9,9967,12,95,84,Delayed,Automation
35,P036,Recruitment,IT,John,2025-06-25,2025-06-25,8,12,4,576,572,99.31,2,1,9716,11,95,81,In Progress,Process Redesign
57,P058,Payroll Processing,Supply Chain,Sarah,2025-12-05,2025-12-05,9,12,4,595,524,88.07,0,5,9691,0,95,81,Completed,Training
27,P028,Procurement,Operations,Mary,2025-04-09,2025-04-09,19,17,5,995,889,89.35,2,8,9352,3,95,75,Delayed,Resource Allocation
40,P041,Recruitment,IT,Emma,2025-11-15,2025-11-15,20,18,9,703,549,78.09,4,9,9308,13,95,97,In Progress,Process Redesign
82,P083,Order Processing,HR,James,2025-05-25,2025-05-25,14,5,4,311,241,77.49,3,9,9258,8,95,87,Delayed,Process Redesign
11,P012,Recruitment,IT,John,2025-10-20,2025-10-20,4,4,5,783,651,83.14,2,0,9110,13,95,77,Delayed,Training
20,P021,Inventory Management,HR,James,2025-11-20,2025-11-20,12,9,6,283,214,75.62,5,7,9004,3,95,76,Delayed,Training
12,P013,Recruitment,IT,Michael,2025-08-06,2025-08-06,15,6,7,970,961,99.07,8,9,8721,11,95,87,Delayed,Process Redesign
30,P031,Procurement,Finance,David,2025-10-11,2025-10-11,16,19,1,580,466,80.34,15,2,8683,2,95,91,In Progress,Training

In [10]:
sla_violations = df[
    df["SLA Achieved"] < 95
]

sla_violations.head()

,Process ID,Process Name,Department,Process Owner,Start Date,End Date,Cycle Time,Standard Cycle Time,Employee Assigned,Task Volume,Tasks Completed,Productivity %,Error Count,Rework Count,Process Cost,Customer Complaints,SLA Target,SLA Achieved,Process Status,Improvement Opportunity
0,P001,Payroll Processing,Supply Chain,Michael,2025-04-13,2025-04-13,21,10,8,960,942,98.12,10,7,6734,9,95,93,Completed,Process Redesign
2,P003,Procurement,Supply Chain,John,2025-09-10,2025-09-10,13,19,9,956,717,75.00,9,2,2899,6,95,94,Delayed,Resource Allocation
4,P005,Invoice Approval,IT,Mary,2025-09-22,2025-09-22,22,17,1,997,788,79.04,14,6,1775,14,95,77,In Progress,Process Redesign
5,P006,Recruitment,Supply Chain,Sarah,2025-02-19,2025-02-19,9,13,2,487,341,70.02,5,5,4843,5,95,92,Completed,Training
8,P009,Invoice Approval,Customer Service,David,2025-06-06,2025-06-06,16,11,8,912,702,76.97,6,8,6463,0,95,86,In Progress,Automation

In [11]:
df.to_csv(
    "Business_Process_Optimization_Dataset.csv",
    index=False
)

print("Dataset Saved Successfully")

Dataset Saved Successfully

In [12]:
from google.colab import files

files.download(
    "Business_Process_Optimization_Dataset.csv"
)